type t = int

let of_string = function
| "acoustic_grand_piano" -> 0
| "bright_acoustic_piano" -> 1
| "electric_grand_piano" -> 2
| "honky-tonk piano" -> 3
| "rhodes_piano" -> 4
| "chorused_piano" -> 5
| "harpsichord" -> 6
| "clavinet" -> 7
| "celesta" -> 8
| "glockenspiel" -> 9
| "music_box" -> 10
| "vibraphone" -> 11
| "marimba" -> 12
| "xylophone" -> 13
| "tubular_bells" -> 14
| "dulcimer" -> 15
| "hammond_organ" -> 16
| "percussive_organ" -> 17
| "rock_organ" -> 18
| "church_organ" -> 19
| "reed_organ" -> 20
| "accordion" -> 21
| "harmonica" -> 22
| "tango_accordion" -> 23
| "acoustic_nylon_guitar" -> 24
| "acoustic_steel_guitar" -> 25
| "electric_jazz_guitar" -> 26
| "electric_clean_guitar" -> 27
| "electric_muted_guitar" -> 28
| "overdriven_guitar" -> 29
| "distortion_guitar" -> 30
| "guitar_harmonics" -> 31
| "acoustic_bass" -> 32
| "fingered_electric_bass" -> 33
| "plucked_electric_bass" -> 34
| "fretless_bass" -> 35
| "slap_bass_1" -> 36
| "slap_bass_2" -> 37
| "synth_bass_1" -> 38
| "synth_bass_2" -> 39
| "violin" -> 40
| "viola" -> 41
| "cello" -> 42
| "contrabass" -> 43
| "tremolo_strings" -> 44
| "pizzicato_strings" -> 45
| "orchestral_harp" -> 46
| "timpani" -> 47
| "string_ensemble_1" -> 48
| "string_ensemble_2" -> 49
| "synth_strings_1" -> 50
| "synth_strings_2" -> 51
| "choir_aah" -> 52
| "choir_ooh" -> 53
| "synth_voice" -> 54
| "orchestra_hit" -> 55
| "trumpet" -> 56
| "trombone" -> 57
| "tuba" -> 58
| "muted_trumpet" -> 59
| "french_horn" -> 60
| "brass_section" -> 61
| "synth_brass_1" -> 62
| "synth_brass_2" -> 63
| "soprano_sax" -> 64
| "alto_sax" -> 65
| "tenor_sax" -> 66
| "baritone_sax" -> 67
| "oboe" -> 68
| "english_horn" -> 69
| "bassoon" -> 70
| "clarinet" -> 71
| "piccolo" -> 72
| "flute" -> 73
| "recorder" -> 74
| "pan_flute" -> 75
| "bottle_blow" -> 76
| "shakuhachi" -> 77
| "whistle" -> 78
| "ocarina" -> 79
| "square_wave_lead" -> 80
| "sawtooth_wave_lead" -> 81
| "calliope_lead" -> 82
| "chiff_lead" -> 83
| "charang_lead" -> 84
| "voice_lead" -> 85
| "fifths_lead" -> 86
| "bass_lead" -> 87
| "new_age_pad" -> 88
| "warm_pad" -> 89
| "polysynth_pad" -> 90
| "choir_pad" -> 91
| "bowed_pad" -> 92
| "metallic_pad" -> 93
| "halo_pad" -> 94
| "sweep_pad" -> 95
| "rain_effect" -> 96
| "soundtrack_effect" -> 97
| "crystal_effect" -> 98
| "atmosphere_effect" -> 99
| "brightness_effect" -> 100
| "goblins_effect" -> 101
| "echoes_effect" -> 102
| "sci-fi_effect" -> 103
| "sitar" -> 104
| "banjo" -> 105
| "shamisen" -> 106
| "koto" -> 107
| "kalimba" -> 108
| "bag_pipe" -> 109
| "fiddle" -> 110
| "shanai" -> 111
| "tinkle_bell" -> 112
| "agogo" -> 113
| "steel_drums" -> 114
| "woodblock" -> 115
| "taiko_drum" -> 116
| "melodic_tom" -> 117
| "synth_drum" -> 118
| "reverse_cymbal" -> 119
| "guitar_fret_noise" -> 120
| "breath_noise" -> 121
| "seashore" -> 122
| "bird_tweet" -> 123
| "telephone_ring" -> 124
| "helicopter" -> 125
| "applause" -> 126
| "gunshot" -> 127
| other -> failwith ("Unknown instrument " ^ other)

let to_midi_code = Fun.id